### ISSUE TITLE
Is this your channel?

### ISSUE THREAD

**Issue by gerrardxcc** [DariusLukasukas/nextjs-weather-app#6]
https://youtu.be/rscl9VwwnQg?si=HpZAMZO0eQygM56q

**Comment by DariusLukasukas** [comment]
Hi gerrardxcc,

Thanks for reaching out! **To clarify, that YouTube channel and associated GitHub repository aren't mine.** Unfortunately, it seems someone took inspiration from my project and created their own version without proper attribution. 😔

**Comment by gerrardxcc** [comment]
That's no good, you should report it to the YouTube and take it down.
